#!/bin/python3

import subprocess
import os
import time
import psutil

start_r = 0
end_r = 0xFF
start_g = 0xFF
end_g = 0
start_b = 0
end_b = 0

while True:
    tot_m, used_m, free_m = map(int, os.popen('free -t -m').readlines()[-1].split()[1:])
    CPU_Pct = max(0.0, min(1.0, psutil.cpu_percent()/100))

    depth = max(0.0, min(1.0, max((used_m / tot_m) ** 1 , (CPU_Pct) ** 1) ** 1))

    target_r = round(start_r + (end_r - start_r) * depth)
    target_g = round(start_g + (end_g - start_g) * depth)
    target_b = round(start_b + (end_b - start_b) * depth)

    #print('{:02X}{:02X}{:02X}'.format(target_r, target_g, target_b), CPU_Pct)
    subprocess.call(['sh', '/usr/local/bin/export-keyboard-color', '{:02X}{:02X}{:02X}'.format(target_r, target_g, target_b)])

    time.sleep(0.05)
